server:
  servlet:
    context-path: /eq-web-server
  port: 28017

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/es?characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
  jpa:
    show-sql: true
  #thymeleaf配置
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    mode: HTML5
    suffix: .html
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379

