
spring:
  profiles:
    active: demo
  thymeleaf:
    cache: false

#日志配置
logging:
  level:
    com.wang.cloud.situation.es.mapper: DEBUG
#   com.wang.cloud.situation.es.mapper: trace 这里可以显示查到的信息


#mybatis配置
#mybatis:
#  configuration:
#    log-impl: com.wang.cloud.situation.es.mapper
#  mapper-locations: classpath:mapper/*/*.xml

